### ISSUE TITLE
Why does it error out?

### ISSUE THREAD

**Issue by OwnDroid** [OwnROM-Devices/android_device_samsung_klte#1]
It says: device/samsung/msm8974-common/msm8974.mk does not excist... 

can you help me?

**Comment by ghost** [comment]
Do you even have a klte anymore?

**Comment by akhilnarang** [comment]
I'll check it out, gimme a few mins

**Comment by akhilnarang** [comment]
@OwnDroid breakfast doesn't work sometimes with devices with many dependencies as the build system looks for some file in more of them, then passed the dependencies to the roomservice.py for fetching
So just clone it, then and then breakfast klte

**Comment by akhilnarang** [comment]
@OwnDroid 
https://github.com/OwnROM-Devices/android_device_samsung_klte/commit/bf7bffb7011ffb5572cf009ede4db1da130d2392
